# Generated by Django 3.2.12 on 2022-02-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=17)),
                ('phone', models.CharField(max_length=12)),
                ('des', models.TextField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
