# Generated by Django 3.2.12 on 2022-02-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='des',
            new_name='desc',
        ),
    ]
